name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'packages/auth/**'

defaults:
  run:
    working-directory: packages/auth


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
      - run: npm install
      - run: npm run build